/* Automatically generated by './build/bin/build-entry.js' */
import './fonts/iconfont.css'
import Statistics from '../packages/statistics/index.js'
import MessageBox from '../packages/message-box/index.js'
import Imageview from '../packages/imageview/index.js'
import Download from '../packages/download/index.js'

const components = [Statistics, Imageview, Download]

// eslint-disable-next-line no-unused-vars
const install = function (Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.1',
  install,
  Statistics,
  MessageBox,
  Imageview,
  Download
}
